# Generated by Django 5.1.1 on 2024-09-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="keywords",
        ),
        migrations.AddField(
            model_name="newspaper",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, related_name="keyword_newspapers", to="news.keyword"
            ),
        ),
    ]
